[phases.setup]
nixPkgs = [
  "python310",
  "ffmpeg",
  "gcc",
  "gnumake",
  "cmake",
  "ninja",
  "clang",
  "pkg-config",
  "libopus",
  "libvpx"
]

[phases.build]
cmds = [
  "pip install wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"